DROP TABLE IF EXISTS Todos 

CREATE TABLE Todos(
    id VARCHAR(200) NOT NULL PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    due_date DATE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);